name: Update Daily Notes

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update_from_leetcode]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install markdown

    - name: Generate notes
      run: python generate_checklist.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add daily_notes/daily_notes_*.md
        git commit -m "Update daily notes"
        git push https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

