name: Generate Daily Checklist

on:
  push:
    paths:
      - '**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        node-version: '20'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install markdown

    - name: Generate checklist
      run: python generate_checklist.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add daily_checklist.md
        git commit -m "Update daily checklist"
        git push https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git
