name: Generate Daily Checklist

on:
  push:
    paths:
      - '**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Use the latest version

    - name: Setup Python
      uses: actions/setup-python@v4  # Use the latest version
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install markdown

    - name: Generate checklist
      run: python generate_checklist.py

    - name: Commit and push changes
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add daily_checklist.md
        git commit -m "Update daily checklist"
        git push https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git
